name: proyecto-aventura
version: 0.0.0.2
description: "Motor de Aventura de Texto"
authors:
  - "Baudilio Velasquez <18-10665@usb.ve>"
  - "Rafael Valera <16-11202@usb.ve>"
maintainer: "18-10665@usb.ve, 16-11202@usb.ve"
copyright: "2025"
license: BSD3

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src
  exposed-modules:
    - Engine.Types
    - Engine.Parser
    - Engine.Core
    - Engine.Persistence

executables:
  proyecto-aventura-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - proyecto-aventura

tests:
  proyecto-aventura-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - proyecto-aventura
      - hspec >= 2.7